// A BraneScript workflow for testing the preprocessing package

import preprocessing;
let data := new Data { name := "heart-disease-raw" };
let data_cleaned := label_encoding(data, ["'HeartDisease'", "'Smoking'"]);
data_cleaned := one_hot_encoding(data_cleaned, ["'AlcoholDrinking'"]);
data_cleaned := ordinal_encoding(data_cleaned, ["'GenHealth'"], [["'Poor'", "'Fair'", "'Good'", "'Very good'", "'Excellent'"]]);